/* eslint-disable */
/**
 * Auto-start the public demo when this machine boots.
 *
 *   npm run autostart            # install (survives reboots)
 *   npm run autostart:status     # is it installed, and is the demo actually up?
 *   npm run autostart:uninstall  # remove it
 *
 * Why this exists
 * ---------------
 * `npm run host` is the one command that makes the public demo work, but it is
 * a foreground process. Close the terminal, log off, or restart the machine and
 * it is gone: the API dies, the Cloudflare quick tunnel dies, and the Worker URL
 * a reviewer was given keeps serving the page while every API call behind it
 * fails. The watcher inside host.js repairs a *lost tunnel*, but nothing repairs
 * a *dead host process* - and a dead host process is what a reboot produces.
 *
 * This closes that gap: a Windows scheduled task runs the host at every logon,
 * wrapped in a retry loop so a crash or a not-yet-ready network heals by
 * itself. Combined with the sleep guard in host.js, the demo then survives the
 * full range of accidents over a short window: reboots, crashes, sleep.
 *
 * It cannot survive a deliberate shutdown. No local process can. For that, see
 * DEPLOY.md and move the API to a real host.
 */
const { spawnSync, spawn } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const TASK_NAME = 'EchoGPT Demo Host';
const HOST_JS = path.join(ROOT, 'scripts', 'host.js');

// The wrapper deliberately lives OUTSIDE the repo, in a path with no spaces.
// schtasks /tr quoting is unreliable for paths containing spaces or brackets,
// and this repo sits in "...\echogpt-backend (1)\echogpt-backend", which has
// both. Keeping the scheduled-task target simple avoids a class of bugs that
// only show up on someone else's machine.
const WRAPPER_DIR = path.join(os.homedir(), 'AppData', 'Local', 'echogpt-demo');
const WRAPPER = path.join(WRAPPER_DIR, 'run.cmd');
const LOG = path.join(ROOT, '.host.log');

const LOCAL_API = 'http://localhost:3001/api/v1/health';

const say = (m) => console.log(m);

function isWindows() {
  return os.platform() === 'win32';
}

function sh(args, opts = {}) {
  return spawnSync('cmd.exe', ['/c', ...args], {
    encoding: 'utf8',
    windowsHide: true,
    ...opts,
  });
}

function taskInstalled() {
  const r = sh(['schtasks', '/Query', '/TN', TASK_NAME, '/FO', 'LIST', '/NH']);
  return r.status === 0;
}

/**
 * Is the API answering right now?
 *
 * Two deliberate details:
 *
 *  1. Use 127.0.0.1, not localhost. On Windows "localhost" resolves to ::1
 *     first, but the server binds IPv4-only (0.0.0.0). Node eventually falls
 *     back to IPv4, but that fallback costs a failed connection attempt - on a
 *     loaded machine that alone can eat a short timeout and report a perfectly
 *     healthy API as down.
 *  2. Retry a few times. A restart in progress looks identical to a dead API
 *     from a single probe, and telling someone their demo is broken when it is
 *     9 seconds into booting is worse than useless.
 */
async function apiIsUp(attempts = 3) {
  const url = LOCAL_API.replace('localhost', '127.0.0.1');
  for (let i = 0; i < attempts; i++) {
    try {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 5000);
      const res = await fetch(url, { signal: ctrl.signal });
      clearTimeout(t);
      if (res.ok) return true;
    } catch (_) {
      /* not up yet */
    }
    if (i < attempts - 1) await new Promise((r) => setTimeout(r, 1500));
  }
  return false;
}

function readPublishedBase() {
  // The demo link is fixed; the tunnel hostname behind it moves. Reading it
  // back out of config.js is how we tell the user what the demo currently
  // points at without guessing.
  try {
    const src = fs.readFileSync(path.join(ROOT, 'frontend', 'config.js'), 'utf8');
    const m = src.match(/apiBase:\s*'([^']+)'/);
    return m ? m[1] : '(not set)';
  } catch (_) {
    return '(config.js unreadable)';
  }
}

function writeWrapper() {
  fs.mkdirSync(WRAPPER_DIR, { recursive: true });

  // Batch, not PowerShell: cmd.exe exists on every Windows install, starts
  // faster, and does not need a script-execution policy decision. Each line
  // that could fail is guarded so one bad step cannot abort the whole run.
  const body = [
    '@echo off',
    'REM -----------------------------------------------------------------------',
    'REM Generated by scripts/autostart.js. Edits here are overwritten on',
    'REM reinstall, so change the generator rather than this file.',
    'REM -----------------------------------------------------------------------',
    'title EchoGPT Demo Host',
    '',
    ':reboot_wait',
    'REM A machine that has just finished logging on is not ready to open a',
    'REM tunnel: the network adapter may still be associating, OneDrive may be',
    'REM syncing, and Defender may be mid-scan. A quick tunnel started too',
    'REM early dies within seconds and takes the demo offline, so wait first.',
    'echo [%DATE% %TIME%] waiting 45s for the network to settle>> "' + LOG + '"',
    'timeout /t 45 /nobreak >nul',
    '',
    ':run',
    'cd /d "' + ROOT + '"',
    'echo [%DATE% %TIME%] starting host.js>> "' + LOG + '"',
    'REM Absolute path to the node binary running this installer. Relying on',
    'REM PATH here is what usually breaks scheduled tasks: a task started at',
    'REM logon does not inherit the user PATH reliably, so bare "node" can',
    'REM fail to resolve even though it works in the terminal.',
    'REM host.js owns its own tunnel recovery; this loop covers the case it',
    'REM cannot: the Node process itself dying.',
    '::  echo off',
    '"' + process.execPath + '" "' + HOST_JS + '" >> "' + LOG + '" 2>&1',
    'echo [%DATE% %TIME%] host.js exited with %ERRORLEVEL%, restarting in 30s>> "' + LOG + '"',
    'timeout /t 30 /nobreak >nul',
    'goto run',
    '',
  ].join('\r\n');

  fs.writeFileSync(WRAPPER, body, 'utf8');
  return WRAPPER;
}

function install() {
  if (!isWindows()) {
    say('This installer is Windows-only (it uses schtasks).');
    say('On macOS/Linux, run `npm run host` in a terminal, or deploy per DEPLOY.md.');
    process.exitCode = 1;
    return;
  }

  if (taskInstalled()) {
    say(`Task "${TASK_NAME}" already exists - re-creating it with current settings.`);
  }

  const wrapper = writeWrapper();

  const r = sh([
    'schtasks',
    '/Create',
    '/TN', TASK_NAME,
    '/TR', wrapper,
    '/SC', 'ONLOGON',
    '/RL', 'LIMITED',
    '/F',
  ]);

  if (r.status !== 0) {
    say('Failed to create the scheduled task:');
    say((r.stderr || r.stdout || '').trim());
    process.exitCode = 1;
    return;
  }

  say(`Installed: "${TASK_NAME}" runs at every logon.`);
  say(`  wrapper : ${wrapper}`);
  say(`  log     : ${LOG}`);
  say('');
  say('What this does and does not cover:');
  say('  restart / crash / logoff  -> host.js restarts, tunnel republishes,');
  say('                               config.js is rewritten, Worker redeployed.');
  say('                              The reviewer URL never changes.');
  say('  sleep                    -> handled inside host.js (it holds a sleep');
  say('                               request while running).');
  say('  shutdown                 -> NOT covered. No local process survives that.');
  say('                              Keep the PC on, or deploy per DEPLOY.md.');
  say('');
  say(`Start it now without waiting for a logon:  schtasks /Run /TN "${TASK_NAME}"`);
  say('Check on it later:                        npm run autostart:status');
}

function uninstall() {
  if (!taskInstalled()) {
    say(`No task named "${TASK_NAME}" is installed - nothing to remove.`);
  } else {
    const r = sh(['schtasks', '/Delete', '/TN', TASK_NAME, '/F']);
    if (r.status !== 0) {
      say('Failed to delete the task: ' + (r.stderr || '').trim());
      process.exitCode = 1;
      return;
    }
    say(`Removed the "${TASK_NAME}" task. The demo will no longer come back on its own.`);
  }
  // Leave the wrapper in place - it is inert, and keeping it makes reinstalling
  // instant. Only remove it if it is genuinely stale, which it never is.
}

async function status() {
  const installed = taskInstalled();

  say('EchoGPT demo host');
  say('------------------');
  say(`auto-start task : ${installed ? 'installed' : 'NOT installed'}`);
  if (installed) {
    const info = sh(['schtasks', '/Query', '/TN', TASK_NAME, '/FO', 'LIST', '/NH']);
    const next = (info.stdout || '').match(/Status:\s*(\S+)/);
    if (next) say(`task status     : ${next[1]}`);
  }

  const up = await apiIsUp();
  say(`local API :3001 : ${up ? 'responding' : 'NOT responding'}`);

  const base = readPublishedBase();
  say(`config.js apiBase: ${base}`);

  if (base.startsWith('http://localhost') || base === '(not set)') {
    say('');
    say('The frontend still points at localhost, so the public demo cannot work yet.');
    say('Run `npm run host` once, or log off and back on to trigger the task.');
  }

  if (!up) {
    say('');
    say('The API is down, so every request from the public demo will fail.');
    if (installed) {
      say(`Try: schtasks /Run /TN "${TASK_NAME}"`);
    } else {
      say('Either run `npm run host`, or install auto-start with `npm run autostart`.');
    }
    say(`Then check ${LOG} for why.`);
  }

  say('');
  say('Public link: https://echogpt.taion16240.workers.dev  (never changes)');
}

const cmd = (process.argv[2] || 'status').toLowerCase();

if (cmd === 'install') install();
else if (cmd === 'uninstall') uninstall();
else if (cmd === 'status') status();
else {
  say(`Unknown command "${cmd}". Use one of: install, uninstall, status`);
  process.exitCode = 1;
}
