/* eslint-disable */
/**
 * One command to run the whole demo. No signup, no accounts, no .env to write.
 *
 *   git clone https://github.com/Ettekhar/echogpt.git
 *   cd echogpt
 *   npm install
 *   npm run demo
 *
 * That is the whole setup. This script exists because every individual piece
 * already worked, but the *first run* did not: a fresh clone has no .env (it is
 * gitignored, correctly), so JWT signing had no secret; scripts/dev.js starts
 * the embedded database but never runs migrations, so the cluster had no tables;
 * and nothing seeded the demo accounts, so there was no way to log in and see
 * anything. A reviewer following the README hit three failures before seeing a
 * single screen.
 *
 * The fix is to remove the steps rather than document them.
 *
 * Design notes worth knowing:
 *
 *  - THE FRONTEND IS SERVED BY THE BACKEND. src/main.ts mounts frontend/ as
 *    static assets, so the page and the API share an origin and app.js falls
 *    back to a same-origin /api/v1. That means no CORS setup, no tunnel, no
 *    wrangler login, and no separate deploy - the reviewer opens one localhost
 *    URL and everything is already connected.
 *
 *  - SECRETS ARE GENERATED, NOT SHIPPED. A fresh clone gets a working .env with
 *    randomly generated JWT and encryption secrets. They are regenerated only if
 *    missing, so an existing .env is never overwritten. The repository is
 *    public, which is exactly why no real key is committed here.
 *
 *  - AN AI KEY IS OPTIONAL, NOT REQUIRED. Without GEMINI_API_KEY the app starts,
 *    seeds, authenticates, and serves the UI; the chat panel explains what is
 *    missing and how to fix it. That is deliberate: requiring a key before the
 *    app boots would mean a reviewer without a key sees a crash instead of a
 *    working product with one feature switched off.
 */
const { spawn, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const net = require('net');
const os = require('os');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const IS_WINDOWS = process.platform === 'win32';
const NPM = IS_WINDOWS ? 'npm.cmd' : 'npm';

const PORT = Number(process.env.PORT) || 3001;
const BASE = `http://localhost:${PORT}`;
const HEALTH = `${BASE}/api/v1/health`;

const say = (m) => console.log(m);
const step = (m) => console.log(`\x1b[36m[setup]\x1b[0m ${m}`);
const ok = (m) => console.log(`\x1b[32m  ok\x1b[0m ${m}`);
const warn = (m) => console.log(`\x1b[33m  !!\x1b[0m ${m}`);

function isPortInUse(port) {
  return new Promise((resolve) => {
    const s = new net.Socket();
    s.setTimeout(700);
    s.once('connect', () => { s.destroy(); resolve(true); });
    s.once('timeout', () => { s.destroy(); resolve(false); });
    s.once('error', () => resolve(false));
    s.connect(port, '127.0.0.1');
  });
}

async function waitForHealth(deadlineMs) {
  const deadline = Date.now() + deadlineMs;
  while (Date.now() < deadline) {
    try {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 2500);
      const res = await fetch(HEALTH, { signal: ctrl.signal });
      clearTimeout(t);
      if (res.ok) return true;
    } catch (_) { /* not yet */ }
    await new Promise((r) => setTimeout(r, 800));
  }
  return false;
}

/**
 * Create a .env with generated secrets if one does not already exist.
 *
 * The values are random per machine on purpose. Sharing a fixed "development
 * secret" in a public repository is the same mistake as sharing a real one, just
 * less likely to be noticed: anyone who reads the repo could mint valid tokens.
 */
function ensureEnv() {
  if (fs.existsSync(ENV_PATH)) {
    ok('.env already exists — leaving it untouched');
    return false;
  }

  const secret = () => crypto.randomBytes(48).toString('hex');
  const encKey = crypto.randomBytes(32).toString('hex');

  const gemini = (process.env.GEMINI_API_KEY || process.env.GEMINI_KEY || '').trim();

  const contents = `# Generated by "npm run demo" on ${new Date().toISOString()}
#
# These secrets were generated locally and are NOT in the repository. Safe to
# delete this file at any time: delete it and run "npm run demo" again.

NODE_ENV=development
PORT=${PORT}
API_PREFIX=api/v1
APP_PUBLIC_URL=${BASE}

DATABASE_URL="postgresql://postgres:password@localhost:5432/echogpt?schema=public"

JWT_ACCESS_SECRET=${secret()}
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_SECRET=${secret()}
JWT_REFRESH_EXPIRES_IN=7d

# Must be 64 hex characters. Used to encrypt stored provider API keys.
PROVIDER_KEY_ENCRYPTION_SECRET=${encKey}

THROTTLE_TTL=60
THROTTLE_LIMIT=100

# The frontend is served from this same origin, so CORS never comes into play
# for the local demo.
CORS_ORIGIN=*

MAIL_HOST=
MAIL_PORT=587
MAIL_USER=
MAIL_PASS=
MAIL_FROM=no-reply@echogpt.app

FREE_PLAN_DAILY_LIMIT=20
PREMIUM_PLAN_DAILY_LIMIT=1000

SEARCH_PROVIDER=serper
SERPER_API_KEY=
BRAVE_SEARCH_API_KEY=

# Optional. Without it everything works except live AI replies, and the chat
# panel says so. Get a key at https://aistudio.google.com/app/apikey and either
# put it here or run:  GEMINI_API_KEY=... npm run demo
GEMINI_API_KEY=${gemini}
GEMINI_DEFAULT_MODEL=gemini-3.8-flash

SEED_ADMIN_PASSWORD=ChangeMe123!
SEED_DEMO_PASSWORD=DemoUser123!
`;

  fs.writeFileSync(ENV_PATH, contents, 'utf8');
  ok('.env created with freshly generated secrets');
  if (gemini) ok('GEMINI_API_KEY taken from your environment');
  return true;
}

/**
 * Read one key out of .env, ignoring quotes and comments.
 *
 * Written as a line loop rather than one regex on purpose. The obvious regex
 * here is a bug: a character class like [^"'\r\n#]* still matches "=", so on an
 * EMPTY value (GEMINI_API_KEY=) the match does not stop at the end of the line -
 * it consumes the newline and returns the whole next line. That reported
 * "GEMINI_DEFAULT_MODEL=gemini-3.8-flash" as the API key: the setup banner
 * claimed a key existed, and the seeder was then handed the same garbage and
 * skipped provider setup. Silent, and it broke chat.
 */
function envValue(key) {
  if (!fs.existsSync(ENV_PATH)) return '';
  for (const raw of fs.readFileSync(ENV_PATH, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    if (line.slice(0, eq).trim() !== key) continue;
    let val = line.slice(eq + 1).trim();
    // Strip one layer of matching quotes, then any trailing inline comment.
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    const hash = val.indexOf(' #');
    if (hash !== -1) val = val.slice(0, hash).trim();
    return val.trim();
  }
  return '';
}

/**
 * Parse .env into process.env for child processes.
 *
 * @nestjs/config loads .env itself, but the Prisma CLI does not read it the same
 * way, and it is read after we may have written the file. Doing it explicitly
 * means migrations and the seeder see identical values to the app.
 */
function loadEnv() {
  if (!fs.existsSync(ENV_PATH)) return;
  for (const line of fs.readFileSync(ENV_PATH, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (!m) continue;
    const key = m[1];
    let val = m[2].trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (val && process.env[key] === undefined) process.env[key] = val;
  }
}

function run(cmd, args, label) {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, {
      cwd: ROOT,
      stdio: 'inherit',
      shell: IS_WINDOWS,
      env: process.env,
    });
    p.on('error', reject);
    p.on('exit', (code) =>
      code === 0 ? resolve() : reject(new Error(`${label} exited with code ${code}`)),
    );
  });
}

async function freePortIfBusy(port) {
  if (!(await isPortInUse(port))) return;
  warn(`port ${port} is busy — stopping whatever is holding it`);
  try {
    if (IS_WINDOWS) {
      const out = spawnSync('netstat', ['-ano', '-p', 'tcp'], { encoding: 'utf8' });
      const pids = new Set();
      for (const line of (out.stdout || '').split(/\r?\n/)) {
        if (line.includes(`:${port}`) && line.includes('LISTENING')) {
          const parts = line.trim().split(/\s+/);
          const pid = parts[parts.length - 1];
          if (pid && pid !== '0' && pid !== String(process.pid)) pids.add(pid);
        }
      }
      for (const pid of pids) spawnSync('taskkill', ['/PID', pid, '/F', '/T'], { stdio: 'ignore' });
    } else {
      spawnSync('bash', ['-c', `fuser -k ${port}/tcp 2>/dev/null || true`]);
    }
    await new Promise((r) => setTimeout(r, 1200));
  } catch (e) {
    warn(`could not free port ${port}: ${e.message}`);
  }
}

function openBrowser() {
  if (process.env.NO_BROWSER) return;
  const url = `${BASE}/`;
  const [cmd, args] =
    os.platform() === 'win32'
      ? ['cmd', ['/c', 'start', '', url]]
      : os.platform() === 'darwin'
        ? ['open', [url]]
        : ['xdg-open', [url]];
  spawn(cmd, args, { stdio: 'ignore', detached: true, shell: os.platform() === 'win32' }).on('error', () => {
    /* headless machine, or no browser — the URL is printed anyway */
  });
}

async function main() {
  console.log('\n\x1b[1mEchoGPT\x1b[0m — self-contained demo');
  console.log('Everything below runs locally. No accounts, no API keys, no deploy.\n');

  step('Configuration');
  ensureEnv();
  loadEnv();

  const hasKey = Boolean(envValue('GEMINI_API_KEY'));
  if (hasKey) {
    ok('Gemini key found — live AI replies will work');
  } else {
    warn('No GEMINI_API_KEY — the app will run fully, but chat will need a key.');
    warn('Get one free at https://aistudio.google.com/app/apikey, then run:');
    warn('  GEMINI_API_KEY=<your key> npm run demo');
  }

  step('Dependencies');
  if (!fs.existsSync(path.join(ROOT, 'node_modules', '@nestjs'))) {
    warn('node_modules looks incomplete — running npm install');
    await run(NPM, ['install'], 'npm install');
  } else {
    ok('node_modules present');
  }

  // The embedded database cluster ships as a platform-specific binary inside
  // embedded-postgres, and npm can silently skip it. When that happens the
  // failure surfaces much later as a confusing "cannot start database", so
  // check for the actual binary now.
  step('Embedded PostgreSQL');
  const hasPgBinary = (() => {
    const dir = path.join(ROOT, 'node_modules', '@embedded-postgres', 'win32-x64');
    if (!fs.existsSync(dir)) return null;
    return fs.readdirSync(dir).some((f) => f.includes('postgres'));
  })();
  if (hasPgBinary === false) {
    warn('the embedded PostgreSQL binary is missing for this platform');
    warn('this usually means npm skipped optional dependencies. Try:');
    warn('  npm install --include=optional');
  } else {
    ok('embedded PostgreSQL binary available');
  }

  step('Database');
  if (await isPortInUse(5432)) {
    ok('PostgreSQL already listening on 5432');
  }

  // Migrations are the step that used to be missing: scripts/dev.js starts the
  // cluster but never migrates, so a fresh clone came up with no tables and
  // every request failed on a missing relation.
  if (fs.existsSync(path.join(ROOT, 'node_modules', '.prisma', 'client'))) {
    ok('Prisma client generated');
  } else {
    step('Generating Prisma client');
    await run(NPM, ['run', 'prisma:generate'], 'prisma generate');
  }

  step('Migrations');
  // migrate deploy needs the server up, and the server is started by dev.js
  // below. So the ordering is: start dev.js (Postgres + app), then migrate,
  // then seed. Migrations applied after boot are fine — the app does not
  // query anything until a request arrives.
  await freePortIfBusy(PORT);

  step('Starting the app');
  const child = spawn(NPM, ['run', 'dev'], {
    cwd: ROOT,
    stdio: ['ignore', 'pipe', 'pipe'],
    shell: IS_WINDOWS,
    env: process.env,
  });
  const passthrough = (stream, tag) => {
    stream.on('data', (b) => {
      const t = b.toString();
      if (IS_WINDOWS) process.stdout.write(t);
      else if (tag) process.stderr.write(t);
    });
  };
  passthrough(child.stdout);
  passthrough(child.stderr);

  let exited = null;
  child.on('exit', (code) => { exited = code; });

  // The database needs a moment to accept connections before Prisma can talk
  // to it, so wait for health first and only then migrate.
  const healthy = await waitForHealth(120_000);
  if (!healthy) {
    console.error('\n[setup] The API did not come up within 120s.');
    if (exited !== null) {
      console.error(`[setup] It exited with code ${exited}. Scroll up for the real error.`);
    } else {
      console.error('[setup] It is still starting. Watch the output above.');
    }
    process.exitCode = 1;
    return;
  }
  ok('API healthy');

  step('Schema');
  try {
    await run(NPM, ['run', 'prisma:deploy'], 'prisma migrate deploy');
    ok('migrations applied');
  } catch (e) {
    // P3005: the database has tables but no migration history. That happens on
    // a database created by "prisma db push". Baseline it and continue instead
    // of failing, because for a demo the end state is what matters.
    if (/P3005|baseline/i.test(e.message)) {
      warn('database has schema but no migration history — baselining');
      await run(NPM, ['exec', 'prisma migrate resolve --applied 20260101000000_init'], 'baseline');
      await run(NPM, ['run', 'prisma:deploy'], 'prisma migrate deploy');
      ok('baselined and migrated');
    } else {
      throw e;
    }
  }

  step('Demo accounts');
  try {
    await run(NPM, ['run', 'seed'], 'seed');
    ok('seeded');
  } catch (e) {
    warn(`seeding failed (${e.message}) — the app still runs, but there is nothing to log in with`);
  }

  const adminPw = envValue('SEED_ADMIN_PASSWORD') || 'ChangeMe123!';
  const demoPw = envValue('SEED_DEMO_PASSWORD') || 'DemoUser123!';

  console.log('\n' + '\x1b[32m' + '='.repeat(64) + '\x1b[0m');
  console.log('\x1b[1m  EchoGPT is running.\x1b[0m');
  console.log('\x1b[32m' + '='.repeat(64) + '\x1b[0m\n');
  console.log(`  App + UI   ${BASE}/`);
  console.log(`  Swagger    ${BASE}/api/v1/docs`);
  console.log(`  Health     ${HEALTH}`);
  console.log('\n  Sign in with either account:');
  console.log(`    admin   admin@echogpt.app   ${adminPw}   (full admin panel)`);
  console.log(`    demo    demo@echogpt.app    ${demoPw}`);
  console.log('\n  The page and the API share this origin, so the UI connects on its own.');
  if (!hasKey) {
    console.log('\n  \x1b[33mChat needs a Gemini key:\x1b[0m');
    console.log('    https://aistudio.google.com/app/apikey  (free)');
    console.log('    then restart with:  GEMINI_API_KEY=<key> npm run demo');
  }
  console.log('\n  Ctrl+C to stop.\n');

  openBrowser();
}

main().catch((e) => {
  console.error('\n[setup] FAILED:', e.message);
  console.error('[setup] The output above should show where it stopped.');
  process.exit(1);
});
